from include.llm_analysis.main_graph import langgraph_app

result = langgraph_app.invoke(
    {
        "title": "Ernest",
        "repo_root_path": "/Users/minkijung/Documents/2PetProjects/ernest",
        "repo_description": "An AI-Powered Review Platform That Gathers Information Through Conversations",
        "packages_used": [
            "datasets",
            "fastapi",
            "huggingface_hub",
            "langchain_core",
            "langchain_openai",
            "langgraph",
            "modal",
            "pydantic",
            "pymongo",
            "ray",
            "tensorrt_llm",
            "torch",
            "transformers",
            "varname",
            "vllmai-sdk/openai",
            "radix-ui/react-alert-dialog",
            "radix-ui/react-dialog",
            "radix-ui/react-dropdown-menu",
            "radix-ui/react-icons",
            "radix-ui/react-label",
            "radix-ui/react-select",
            "radix-ui/react-separator",
            "radix-ui/react-slot",
            "radix-ui/react-switch",
            "radix-ui/react-tooltip",
            "vercel/analytics",
            "vercel/kv",
            "vercel/og",
            "vis.gl/react-google-maps",
            "ai",
            "class-variance-authority",
            "clsx",
            "d3-scale",
            "date-fns",
            "focus-trap-react",
            "framer-motion",
            "geist",
            "googlemaps",
            "mongodb",
            "nanoid",
            "next",
            "next-auth",
            "next-themes",
            "openai",
            "react",
            "react-dom",
            "react-intersection-observer",
            "react-markdown",
            "react-syntax-highlighter",
            "react-textarea-autosize",
            "remark-gfm",
            "remark-math",
            "sonner",
            "usehooks-ts",
            "zod",
        ],
        "directory_tree": """├── .gitignore\n├── README.md\n├── backend\n│ ├── .DS_Store\n│ ├── __pycache__\n│ │ ├── common.cpython-312.pyc\n│ │ ├── compile.cpython-312.pyc\n│ │ ├── inference.cpython-312.pyc\n│ │ ├── questions.cpython-312.pyc\n│ │ ├── signatures.cpython-312.pyc\n│ │ ├── validations.cpython-312.pyc\n│ ├── app\n│ │ ├── .DS_Store\n│ │ ├── __init__.py\n│ │ ├── __pycache__\n│ │ │ ├── __init__.cpython-311.pyc\n│ │ │ ├── __init__.cpython-312.pyc\n│ │ │ ├── common.cpython-312.pyc\n│ │ │ ├── main.cpython-311.pyc\n│ │ │ ├── main.cpython-312.pyc\n│ │ ├── api\n│ │ │ ├── .DS_Store\n│ │ │ ├── __init__.py\n│ │ │ ├── __pycache__\n│ │ │ │ ├── __init__.cpython-312.pyc\n│ │ │ │ ├── main.cpython-312.pyc\n│ │ │ ├── main.py\n│ │ │ ├── routes\n│ │ │ │ ├── __init__.py\n│ │ │ │ ├── __pycache__\n│ │ │ │ │ ├── __init__.cpython-312.pyc\n│ │ │ │ │ ├── chat.cpython-312.pyc\n│ │ │ │ │ ├── compile.cpython-312.pyc\n│ │ │ │ │ ├── conversation.cpython-312.pyc\n│ │ │ │ │ ├── history.cpython-312.pyc\n│ │ │ │ │ ├── inference.cpython-312.pyc\n│ │ │ │ │ ├── local_llm.cpython-312.pyc\n│ │ │ │ ├── chat.py\n│ │ │ │ ├── db.py\n│ │ ├── common.py\n│ │ ├── dspy\n│ │ │ ├── .DS_Store\n│ │ │ ├── __pycache__\n│ │ │ │ ├── compile.cpython-312.pyc\n│ │ │ │ ├── signatures.cpython-312.pyc\n│ │ │ │ ├── validations.cpython-312.pyc\n│ │ │ ├── compiled\n│ │ │ │ ├── intent_classifier.json\n│ │ │ │ ├── rag.json\n│ │ │ ├── lm_clients\n│ │ │ │ ├── __pycache__\n│ │ │ │ │ ├── llama3_8b.cpython-312.pyc\n│ │ │ │ ├── llama3_8b.py\n│ │ │ ├── modules\n│ │ │ │ ├── __pycache__\n│ │ │ │ │ ├── chatbot.cpython-312.pyc\n│ │ │ │ │ ├── intent_classifier.cpython-312.pyc\n│ │ │ │ │ ├── rag.cpython-312.pyc\n│ │ │ │ │ ├── simplified_baleen.cpython-312.pyc\n│ │ │ │ ├── chatbot.py\n│ │ │ │ ├── intent_classifier.py\n│ │ │ │ ├── rag.py\n│ │ │ │ ├── simplified_baleen.py\n│ │ │ ├── optimizers\n│ │ │ │ ├── __pycache__\n│ │ │ │ │ ├── compile.cpython-312.pyc\n│ │ │ │ │ ├── intent_classifier.cpython-312.pyc\n│ │ │ │ │ ├── rag.cpython-312.pyc\n│ │ │ │ ├── intent_classifier.py\n│ │ │ │ ├── rag.py\n│ │ │ ├── signatures\n│ │ │ │ ├── __pycache__\n│ │ │ │ │ ├── signatures.cpython-312.pyc\n│ │ │ │ ├── signatures.py\n│ │ │ ├── utils\n│ │ │ │ ├── __pycache__\n│ │ │ │ │ ├── download_dataset.cpython-312.pyc\n│ │ │ │ │ ├── initialize_DSPy.cpython-312.pyc\n│ │ │ │ │ ├── load_compiled_module.cpython-312.pyc\n│ │ │ │ │ ├── load_dataset.cpython-312.pyc\n│ │ │ │ │ ├── print_history.cpython-312.pyc\n│ │ │ │ ├── initialize_DSPy.py\n│ │ │ │ ├── load_compiled_module.py\n│ │ │ │ ├── load_dataset.py\n│ │ │ │ ├── print_history.py\n│ │ │ ├── validations\n│ │ │ │ ├── __pycache__\n│ │ │ │ │ ├── validations.cpython-312.pyc\n│ │ │ │ ├── validations.py\n│ │ ├── langchain\n│ │ │ ├── .DS_Store\n│ │ │ ├── __pycache__\n│ │ │ │ ├── common.cpython-312.pyc\n│ │ │ │ ├── langgraph_main.cpython-312.pyc\n│ │ │ │ ├── main.cpython-312.pyc\n│ │ │ │ ├── main_graph.cpython-312.pyc\n│ │ │ │ ├── reply_chat.cpython-312.pyc\n│ │ │ │ ├── schema.cpython-312.pyc\n│ │ │ ├── common.py\n│ │ │ ├── conditional_edges\n│ │ │ │ ├── __pycache__\n│ │ │ │ │ ├── pick_by_llm.cpython-312.pyc\n│ │ │ │ │ ├── simple_check.cpython-312.pyc\n│ │ │ │ ├── llm\n│ │ │ │ │ ├── __pycache__\n│ │ │ │ │ │ ├── plan.cpython-312.pyc\n│ │ │ │ │ │ ├── routers.cpython-312.pyc\n│ │ │ │ │ ├── check.py\n│ │ │ │ │ ├── reflect.py\n│ │ │ │ ├── non_llm\n│ │ │ │ │ ├── __pycache__\n│ │ │ │ │ │ ├── routers.cpython-312.pyc\n│ │ │ │ │ │ ├── simple_check.cpython-312.pyc\n│ │ │ │ │ ├── simple_check.py\n│ │ │ │ ├── old_edges.py\n│ │ │ ├── main_graph.py\n│ │ │ ├── nodes\n│ │ │ │ ├── __pycache__\n│ │ │ │ │ ├── check.cpython-312.pyc\n│ │ │ │ │ ├── decide.cpython-312.pyc\n│ │ │ │ │ ├── generate.cpython-312.pyc\n│ │ │ │ │ ├── state_control.cpython-312.pyc\n│ │ │ │ │ ├── update.cpython-312.pyc\n│ │ │ │ ├── llm\n│ │ │ │ │ ├── __pycache__\n│ │ │ │ │ │ ├── criticize.cpython-312.pyc\n│ │ │ │ │ │ ├── decide.cpython-312.pyc\n│ │ │ │ │ │ ├── extract.cpython-312.pyc\n│ │ │ │ │ │ ├── find.cpython-312.pyc\n│ │ │ │ │ │ ├── generate.cpython-312.pyc\n│ │ │ │ │ │ ├── pick.cpython-312.pyc\n│ │ │ │ │ │ ├── plan.cpython-312.pyc\n│ │ │ │ │ ├── criticize.py\n│ │ │ │ │ ├── decide.py\n│ │ │ │ │ ├── extract.py\n│ │ │ │ │ ├── find.py\n│ │ │ │ │ ├── generate.py\n│ │ │ │ │ ├── pick.py\n│ │ │ │ ├── non_llm\n│ │ │ │ │ ├── __pycache__\n│ │ │ │ │ │ ├── gather_context.cpython-312.pyc\n│ │ │ │ │ │ ├── predefined_reply.cpython-312.pyc\n│ │ │ │ │ │ ├── state_control.cpython-312.pyc\n│ │ │ │ │ ├── gather_context.py\n│ │ │ │ │ ├── neo4j_graph_query.py\n│ │ │ │ │ ├── predefined_reply.py\n│ │ │ │ │ ├── state_control.py\n│ │ │ │ │ ├── tournament_stage.py\n│ │ │ │ │ ├── update.py\n│ │ │ │ ├── old_nodes.py\n│ │ │ │ ├── readme.md\n│ │ │ ├── schema.py\n│ │ │ ├── subgraphs\n│ │ │ │ ├── ask_vendor_info\n│ │ │ │ │ ├── graph.py\n│ │ │ │ ├── end_of_chat\n│ │ │ │ │ ├── __pycache__\n│ │ │ │ │ │ ├── graph.cpython-312.pyc\n│ │ │ │ │ │ ├── main.cpython-312.pyc\n│ │ │ │ │ ├── graph.py\n│ │ │ │ ├── middle_of_chat\n│ │ │ │ │ ├── __pycache__\n│ │ │ │ │ │ ├── graph.cpython-312.pyc\n│ │ │ │ │ │ ├── main.cpython-312.pyc\n│ │ │ │ │ ├── extract\n│ │ │ │ │ │ ├── __pycache__\n│ │ │ │ │ │ │ ├── graph.cpython-312.pyc\n│ │ │ │ │ │ ├── graph.py\n│ │ │ │ │ ├── gather_context\n│ │ │ │ │ │ ├── __pycache__\n│ │ │ │ │ │ │ ├── graph.cpython-312.pyc\n│ │ │ │ │ │ │ ├── main.cpython-312.pyc\n│ │ │ │ │ │ ├── graph.py\n│ │ │ │ │ ├── graph.py\n│ │ │ │ │ ├── graph_agent\n│ │ │ │ │ │ ├── graph.py\n│ │ │ │ ├── start_of_chat\n│ │ │ │ │ ├── __pycache__\n│ │ │ │ │ │ ├── graph.cpython-312.pyc\n│ │ │ │ │ │ ├── main.cpython-312.pyc\n│ │ │ │ │ ├── graph.py\n│ │ │ │ ├── utils\n│ │ │ │ │ ├── tournament.py\n│ │ │ ├── utils\n│ │ │ │ ├── __pycache__\n│ │ │ │ │ ├── converters.cpython-312.pyc\n│ │ │ │ │ ├── messages_to_string.cpython-312.pyc\n│ │ │ │ ├── converters.py\n│ │ │ │ ├── neo4j.py\n│ │ ├── local_llms\n│ │ │ ├── .DS_Store\n│ │ │ ├── __pycache__\n│ │ │ │ ├── llama3_8b.cpython-312.pyc\n│ │ │ │ ├── llama3_8b_on_vllm.cpython-312.pyc\n│ │ │ ├── llama3_8b.py\n│ │ │ ├── llama3_8b_on_tensorRT.py\n│ │ │ ├── llama3_8b_on_vllm.py\n│ │ ├── main.py\n│ │ ├── public\n│ │ │ ├── __pycache__\n│ │ │ │ ├── questions.cpython-312.pyc\n│ │ │ ├── questions.py\n│ │ ├── schemas\n│ │ │ ├── __pycache__\n│ │ │ │ ├── schemas.cpython-312.pyc\n│ │ │ ├── schemas.py\n│ │ ├── test_notebooks\n│ │ │ ├── .DS_Store\n│ │ │ ├── __pycache__\n│ │ │ │ ├── tweet_metric.cpython-312.pyc\n│ │ │ ├── cache.db\n│ │ │ ├── compiling_langchain.ipynb\n│ │ │ ├── conditional_edges_test.ipynb\n│ │ │ ├── langgraph_dspy.ipynb\n│ │ │ ├── parallel_node.ipynb\n│ │ │ ├── pydantic_test.ipynb\n│ │ │ ├── stable_sorting.ipynb\n│ │ │ ├── trainset.json\n│ │ │ ├── tweet_metric.py\n│ │ ├── utils\n│ │ │ ├── .DS_Store\n│ │ │ ├── __pycache__\n│ │ │ │ ├── default_questions.cpython-312.pyc\n│ │ │ │ ├── default_topics.cpython-312.pyc\n│ │ │ │ ├── dspy_initialize.cpython-312.pyc\n│ │ │ │ ├── mongodb.cpython-312.pyc\n│ │ │ │ ├── twilio.cpython-312.pyc\n│ │ │ ├── mongodb.py\n│ │ │ ├── twilio.py\n│ ├── graph_imgs\n│ │ ├── main_graph.png\n│ │ ├── middle_of_chat.png\n│ │ ├── tournament.png\n│ ├── readme.md\n│ ├── requirements.txt\n├── frontend\n│ ├── .DS_Store\n│ ├── .eslintrc.json\n│ ├── .gitignore\n│ ├── NOTICE\n│ ├── README.md\n│ ├── app\n│ │ ├── (chat)\n│ │ │ ├── chat\n│ │ │ │ ├── [id]\n│ │ │ │ │ ├── page.tsx\n│ │ │ ├── layout.tsx\n│ │ │ ├── page.tsx\n│ │ ├── .DS_Store\n│ │ ├── actions.ts\n│ │ ├── api\n│ │ │ ├── auth\n│ │ │ │ ├── callback\n│ │ │ │ │ ├── google\n│ │ │ │ │ │ ├── route.ts\n│ │ ├── globals.css\n│ │ ├── layout.tsx\n│ │ ├── login\n│ │ │ ├── actions.ts\n│ │ │ ├── page.tsx\n│ │ ├── new\n│ │ │ ├── page.tsx\n│ │ ├── reviews\n│ │ │ ├── layout.tsx\n│ │ │ ├── page.tsx\n│ │ │ ├── review\n│ │ │ │ ├── [id]\n│ │ │ │ │ ├── page.tsx\n│ │ ├── share\n│ │ │ ├── [id]\n│ │ │ │ ├── page.tsx\n│ │ ├── signup\n│ │ │ ├── actions.ts\n│ │ │ ├── page.tsx\n│ ├── auth.config.ts\n│ ├── auth.ts\n│ ├── components\n│ │ ├── .DS_Store\n│ │ ├── button-scroll-to-bottom.tsx\n│ │ ├── chat-history.tsx\n│ │ ├── chat-list.tsx\n│ │ ├── chat-message-actions.tsx\n│ │ ├── chat-message.tsx\n│ │ ├── chat-panel.tsx\n│ │ ├── chat-share-dialog.tsx\n│ │ ├── chat.tsx\n│ │ ├── clear-history.tsx\n│ │ ├── empty-screen.tsx\n│ │ ├── external-link.tsx\n│ │ ├── footer.tsx\n│ │ ├── header.tsx\n│ │ ├── login-button.tsx\n│ │ ├── login-form.tsx\n│ │ ├── markdown.tsx\n│ │ ├── prompt-form.tsx\n│ │ ├── providers.tsx\n│ │ ├── review-card.tsx\n│ │ ├── sidebar-actions.tsx\n│ │ ├── sidebar-desktop.tsx\n│ │ ├── sidebar-footer.tsx\n│ │ ├── sidebar-item.tsx\n│ │ ├── sidebar-items.tsx\n│ │ ├── sidebar-list.tsx\n│ │ ├── sidebar-mobile.tsx\n│ │ ├── sidebar-toggle.tsx\n│ │ ├── sidebar.tsx\n│ │ ├── signup-form.tsx\n│ │ ├── stocks\n│ │ │ ├── events-skeleton.tsx\n│ │ │ ├── events.tsx\n│ │ │ ├── google-map-picker.tsx\n│ │ │ ├── index.tsx\n│ │ │ ├── message.tsx\n│ │ │ ├── pick-vendor.tsx\n│ │ │ ├── spinner.tsx\n│ │ │ ├── stock-purchase.tsx\n│ │ │ ├── stock-skeleton.tsx\n│ │ │ ├── stock.tsx\n│ │ │ ├── stocks-skeleton.tsx\n│ │ │ ├── stocks.tsx\n│ │ ├── tailwind-indicator.tsx\n│ │ ├── theme-toggle.tsx\n│ │ ├── ui\n│ │ │ ├── alert-dialog.tsx\n│ │ │ ├── badge.tsx\n│ │ │ ├── button.tsx\n│ │ │ ├── card.tsx\n│ │ │ ├── codeblock.tsx\n│ │ │ ├── dialog.tsx\n│ │ │ ├── dropdown-menu.tsx\n│ │ │ ├── icons.tsx\n│ │ │ ├── input.tsx\n│ │ │ ├── label.tsx\n│ │ │ ├── select.tsx\n│ │ │ ├── separator.tsx\n│ │ │ ├── sheet.tsx\n│ │ │ ├── sonner.tsx\n│ │ │ ├── switch.tsx\n│ │ │ ├── textarea.tsx\n│ │ │ ├── tooltip.tsx\n│ │ ├── user-menu.tsx\n│ ├── components.json\n│ ├── lib\n│ │ ├── .DS_Store\n│ │ ├── chat\n│ │ │ ├── actions.tsx\n│ │ ├── hooks\n│ │ │ ├── use-copy-to-clipboard.tsx\n│ │ │ ├── use-enter-submit.tsx\n│ │ │ ├── use-local-storage.ts\n│ │ │ ├── use-scroll-anchor.tsx\n│ │ │ ├── use-sidebar.tsx\n│ │ │ ├── use-streamable-text.ts\n│ │ ├── mongodb.ts\n│ │ ├── types.ts\n│ │ ├── utils.ts\n│ ├── middleware.ts\n│ ├── next-env.d.ts\n│ ├── next.config.js\n│ ├── package-lock.json\n│ ├── package.json\n│ ├── pnpm-lock.yaml\n│ ├── postcss.config.js\n│ ├── prettier.config.cjs\n│ ├── public\n│ │ ├── apple-touch-icon.png\n│ │ ├── ernest_logo.png\n│ │ ├── favicon-16x16.png\n│ │ ├── favicon.ico\n│ ├── tailwind.config.ts\n│ ├── tsconfig.json\n├── scripts\n│ ├── Graph_RAG_example.ipynb\n│ ├── RAG.ipynb\n│ ├── chroma_test.ipynb\n│ ├── graph_database_test_neo4j.ipynb\n│ ├── graph_database_test_whyhow copy.ipynb\n│ ├── graph_legend.png\n│ ├── graph_visualization.png\n│ ├── review_preprocessing.ipynb\n│ ├── sample_pdf.pdf\n│ ├── scrapped_reviews\n│ │ ├── reviews.csv\n│ │ ├── reviews_selected.csv\n│ │ ├── reviews_selected_schema.json\n│ │ ├── reviews_selected_small.csv\n│ │ ├── reviews_selected_small_topics.csv\n│ │ ├── salon_list.csv\n│ │ ├── vectorized\n│ │ │ ├── chroma.sqlite3\n│ │ │ ├── edd934fe-37ac-44cf-ac8e-32b8695eb5e6\n│ │ │ │ ├── data_level0.bin\n│ │ │ │ ├── header.bin\n│ │ │ │ ├── index_metadata.pickle\n│ │ │ │ ├── length.bin\n│ │ │ │ ├── link_lists.bin\n│ ├── topic_list.json\n│ ├── vectorstore\n│ │ ├── 7a848e91-b158-44d7-9dfb-8f0ee773e46f\n│ │ │ ├── data_level0.bin\n│ │ │ ├── header.bin\n│ │ │ ├── length.bin\n│ │ │ ├── link_lists.bin\n│ │ ├── chroma.sqlite3\n""",
        "steps": [],
        "analysis_results": [],
    }
)

# print(result)
